
#ifndef COSC_ASSIGN_TWO_TYPES
#define COSC_ASSIGN_TWO_TYPES

#include "Tile.h"
#include <vector>

// TILE COLORS
#define FIRST_TILE 'F'
#define RED 'R'
#define YELLOW 'Y'
#define DARK_BLUE 'B'
#define LIGHT_BLUE 'L'
#define BLACK 'U'
#define ORANGE 'O'

// DEFAULT AND GREY BOARD GAME VALUES
#define MAX_GAME_ROUNDS 5
#define MOSAIC_DIM 5
#define MOSAIC_BOARD_SIZE (MOSAIC_DIM * MOSAIC_DIM)
#define BROKEN_ROW_SIZE 7
#define MOSAIC_BOARD_COLOR "byrullbyruulbyrrulbyyrulb"
#define NORMAL_ALL_TILES "BBBBBBBBBBBBBBBBBBBBUUUUUUUUUUUUUUUUUUUULLLLLLLLLLLLLLLLLLLLYYYYYYYYYYYYYYYYYYYYRRRRRRRRRRRRRRRRRRRR"

// COMMON VALUES
#define NUM_OF_PLAYERS 2
#define NUM_OF_FACTORIES 5
#define FACTORY_SIZE 4
#define FIRST_FACTORY 0
#define LAST_FACTORY 5
#define FIRST_STORAGE_ROW 0
#define LAST_STORAGE_ROW 5
#define INVALID_COORDINATE -2
#define MAX_TILE_NUM 20
#define VALID_CHARS "RYBLU"
#define TILE_BAG_VALID_CHARS "RYBLUF"
#define MAX_DIRECTIONS 4
#define MAX_UP 0
#define MAX_DOWN 4
#define MAX_RIGHT 4
#define MAX_LEFT 0
#define NUM_OF_TILES_IN_TILE_BAG 100
#define WHITESPACE ' '
#define DOUBLE_WHITESPACE "  "
#define NO_TILE '.'
#define END_OF_FILE '\0'


#define DEFAULT_NAME "default"

// FLAGS AND HEADERS
#define RANDOM_MODE_HEADER "#random"
#define ADVANCED_MODE_HEADER "#adv"
#define SIX_TILE_MODE_FLAG "six"
#define GREY_BOARD_MODE_FLAG "grey"

#endif // COSC_ASSIGN_TWO_TYPES
